db:
  image: postgres
web:
  build: .
  command: python manage.py runserver 0.0.0.0:8000
  environment:
    SITE_ENV: dev
  volumes:
    - .:/code
  ports:
    - "8890:8000"
  links:
    - db
angular:
  image: httpd:latest
  ports:
    - "8889:80"
  links:
    - web
  volumes:
    - ./frontend:/usr/local/apache2/htdocs/
