# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 13:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import meta.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_id', models.CharField(default=meta.models.generate_id, editable=False, max_length=32, unique=True)),
                ('uid', models.CharField(editable=False, max_length=32, unique=True)),
                ('sequencing_platform', models.CharField(choices=[(b'Illumina', b'Illumina'), (b'Ion Torrent', b'Ion Torrent')], max_length=255)),
                ('sequencing_type', models.CharField(choices=[(b'single', b'single'), (b'paired', b'paired'), (b'mate-paired', b'mate-paired'), (b'unknown', b'unknown')], max_length=255)),
                ('pre_assembled', models.CharField(choices=[(b'yes', b'yes'), (b'no', b'no')], max_length=255)),
                ('isolation_source', models.CharField(choices=[(b'human', b'human'), (b'water', b'water'), (b'food', b'food'), (b'animal', b'animal'), (b'other', b'other'), (b'laboratory', b'laboratory')], max_length=255)),
                ('pathogenic', models.CharField(choices=[(b'yes', b'yes'), (b'no', b'no'), (b'unknown', b'unknown')], max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('sample_name', models.CharField(max_length=255, null=True)),
                ('longitude', models.CharField(max_length=255, null=True)),
                ('latitude', models.CharField(max_length=255, null=True)),
                ('organism', models.CharField(max_length=255, null=True)),
                ('strain', models.CharField(max_length=255, null=True)),
                ('subtype', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('zip_code', models.CharField(max_length=255, null=True)),
                ('location_note', models.CharField(max_length=255, null=True)),
                ('source_note', models.CharField(max_length=255, null=True)),
                ('pathogenicity_note', models.CharField(max_length=255, null=True)),
                ('collected_by', models.CharField(max_length=255, null=True)),
                ('email_address', models.EmailField(max_length=255, null=True)),
                ('notes', models.TextField(max_length=255, null=True)),
                ('usage_restrictions', models.CharField(choices=[(b'private', b'private'), (b'public', b'public')], max_length=255, null=True)),
                ('collection_date', models.CharField(max_length=255)),
                ('release_date', models.EmailField(max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
