# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='host',
            field=models.CharField(choices=[(b'human', b'human'), (b'water', b'water'), (b'food', b'food'), (b'animal', b'animal'), (b'other', b'other'), (b'laboratory', b'laboratory')], default='other', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metadata',
            name='isolation_source',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='sequencing_platform',
            field=models.CharField(choices=[(b'illumina', b'illumina'), (b'ion torrent', b'ion torrent')], max_length=255),
        ),
    ]
