"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 1.9.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import datetime
from django.conf import settings
from .settings import *


DEBUG = False

TEMPLATE_DEBUG = False

ALLOWED_HOSTS = [
  'compare.cbs.dtu.dk'
]

CORS_ORIGIN_WHITELIST = (
    'compare.cbs.dtu.dk',
    'compare.cbs.dtu.dk/compareAPI',
    'compare.cbs.dtu.dk/compareAPI/',
    'compare.cbs.dtu.dk/portal',
    'compare.cbs.dtu.dk/portal/',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware'
)

# Database
# https://docs.djangoproject.com/en/1.6/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'postgres',
        'USER': 'postgres',
        'HOST': 'db',
        'PORT': 5432,
    }
}

APPEND_SLASH = False

CORS_ALLOW_HEADERS = (
        'x-requested-with',
        'content-type',
        'accept',
        'origin',
        'authorization',
        'x-csrftoken',
        'Content-Range',
        'HTTP_CONTENT_RANGE',
        'CONTENT_RANGE',
        'X-Forwarded-Host',
        'X-Forwarded-Port',
        'X-Forwarded-For',
        'X-Forwarded-Scheme'
    )
